//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XamarinApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppContentText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppContentText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XamarinApp.Resources.AppContentText", typeof(AppContentText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication Failed.
        /// </summary>
        internal static string Authentication_Failed {
            get {
                return ResourceManager.GetString("Authentication Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or password are incorrect. Try again!.
        /// </summary>
        internal static string Email_or_password_are_incorrect__Try_again_ {
            get {
                return ResourceManager.GetString("Email or password are incorrect. Try again!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or passwords are incorrect. Try again!.
        /// </summary>
        internal static string Email_or_passwords_are_incorrect__Try_again_ {
            get {
                return ResourceManager.GetString("Email or passwords are incorrect. Try again!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string HomeTab {
            get {
                return ResourceManager.GetString("HomeTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main settings.
        /// </summary>
        internal static string MainSettingsTitle {
            get {
                return ResourceManager.GetString("MainSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        internal static string MapTab {
            get {
                return ResourceManager.GetString("MapTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must match..
        /// </summary>
        internal static string Passwords_must_match_ {
            get {
                return ResourceManager.GetString("Passwords must match.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register now.
        /// </summary>
        internal static string Register_now {
            get {
                return ResourceManager.GetString("Register now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Failed.
        /// </summary>
        internal static string Registration_Failed {
            get {
                return ResourceManager.GetString("Registration Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select FontFamily.
        /// </summary>
        internal static string SelectFontFamilyPlaceholder {
            get {
                return ResourceManager.GetString("SelectFontFamilyPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select FontSize.
        /// </summary>
        internal static string SelectFontSizePlaceholder {
            get {
                return ResourceManager.GetString("SelectFontSizePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select language.
        /// </summary>
        internal static string SelectLanguagePlaceholder {
            get {
                return ResourceManager.GetString("SelectLanguagePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsTab {
            get {
                return ResourceManager.GetString("SettingsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        internal static string Sign_in {
            get {
                return ResourceManager.GetString("Sign in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in to your account.
        /// </summary>
        internal static string Sign_in_to_your_account {
            get {
                return ResourceManager.GetString("Sign in to your account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        internal static string Sign_up {
            get {
                return ResourceManager.GetString("Sign up", resourceCulture);
            }
        }
    }
}
